// iconMap.js

import {
  faCoffee,
  faHeart,
  faHandshake,
  faUser,
  faSeedling,
  faAngleRight,
  faAngleLeft,
  faBars,
  faXmark,
  faPaperPlane,
  faHandHoldingHeart,
  faArrowDown,
  faGraduationCap,
  faHandsHelping,
  faDonate,
  faUsers,
  faCheck,
  faQuoteLeft,
  faArrowRight,
  faLeaf,
  faLock,
  faShield,
  faArrowUp,
  faHeartbeat,
  faVenus,
  faUserGraduate,
  faTree,
  faHome,
  faBookOpen,
  faCheckCircle,
  faExclamationCircle,
  faMapMarkedAlt,
  faMapMarkerAlt,
  faPhoneAlt,
  faEnvelope,
  faClock,
} from "@fortawesome/free-solid-svg-icons";
import {
  faFacebook,
  faTwitter,
  faInstagram,
  faLinkedin,
  faGithub,
} from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
export const iconMap = {
  coffee: faCoffee,
  heart: faHeart,
  handshake: faHandshake,
  user: faUser,
  seedling: faSeedling,
  rightMove: faAngleRight,
  leftMove: faAngleLeft,
  bar: faBars,
  xmark: faXmark,
  twitter: faTwitter,
  facebook: faFacebook,
  instagram: faInstagram,
  linkedin: faLinkedin,
  github: faGithub,
  paperplane: faPaperPlane,
  HeartInHand: faHandHoldingHeart,
  arrowdown: faArrowDown,
  graduationCap: faGraduationCap,
  handsHelping: faHandsHelping,
  donate: faDonate,
  users: faUsers,
  check: faCheck,
  quoteLeft: faQuoteLeft,
  arrowRight: faArrowRight,
  leaf: faLeaf,
  lock: faLock,
  sheild: faShield,
  arrowup: faArrowUp,
  heartbeat: faHeartbeat,
  venus: faVenus,
  userGraduate:faUserGraduate,
  tree:faTree,
  home:faHome,
  bookOpen:faBookOpen,
  checkCircle:faCheckCircle,
  exclamationCircle:faExclamationCircle,
  mapMarkerAlt:faMapMarkerAlt,
  phoneAlt:faPhoneAlt,
  envelope:faEnvelope,
  clock:faClock,
};
